inherit_from: .rubocop_todo.yml

Documentation:
  Enabled: false

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'config/initializers/**/*'
Metrics/BlockLength:
  Exclude:
    - 'app/apis/**/*.rb'
    - 'lib/tasks/**/*.rake'
Style/WordArray:
  EnforcedStyle: brackets
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table


