default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: syft_coding_challenge_development

test:
  <<: *default
  database: syft_coding_challenge_test
  pool: 15